### ISSUE TITLE
Aes 128 or Aes 256 ?

### ISSUE THREAD

**Issue by redorc15** [ahmednooor/KrypApp#1]
Hi ! your work is so great !! i just look at the source code and i think that crypter use Aes 128 !
i'll be thankfull if you change it to Aes 256 :) !!

may that help you :+1: 
from Crypto.Random import get_random_bytes
self.user_key = get_random_bytes(32) # 32 bytes * 8 = 256 bits (1 byte = 8 bits)

Remarque : I tried that code and (32) and (24) with same password i'll get same ciphertext !

I'am waiting for you response ! Thanks !

**Comment by ahmednooor** [comment]
@redorc15 
Hi, thank you for your interest. I think what you are saying can be achieved by changing this,
https://github.com/ahmednooor/KrypApp/blob/master/KrypApp.py#L97
``` python
self.hashed_key_salt["key"] = bytes(hasher.hexdigest()[:16], "utf-8")
```

into this,
``` python
self.hashed_key_salt["key"] = bytes(hasher.hexdigest()[:32], "utf-8")
```

The resultant hash will be 32 bytes (256 bits) long. Let me know if that is what you meant. Thank you.

P.S. I don't think we can use random bytes because the key is dependent on user input hence the reason to convert any user inputted key into a hash and using that instead.

**Comment by redorc15** [comment]
Okey i understand now how it works :) ! i just changed to 
self.hashed_key_salt["key"] = bytes(hasher.hexdigest()[:32], "utf-8")
and i encreyped 2 files with same password now i get différent ciphertext ! wich mean it works :)
( now it use AES CFB 256 ).
Thank you very much !!
+
i've other question why you use Aes cfb ? i think Aes Gcm is better !

Remarque : i changed it to Aes GCM and it works fine but its better if we add password authentication ( if password is wrong it will appear msgbox says wrong password ! )

Waiting for your response !

**Comment by ahmednooor** [comment]
I am not a cryptography person so I can't answer from a cryptographic perspective. I picked the encryption related class from somewhere (read credits in readme) and wrapped a tkinter GUI around it. I was experimenting with GUI side of python and thought of it being a good use case.

Closing this issue now. I will update the 16 byte to 32 byte key soon.
Thank you for your interest. Take care :)
